# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\n\n\x08\x45mptyTwo\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"4\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.Dates\"%\n\x05\x44\x61tes\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"/\n\x0fShowtimeDataTwo\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x1b\n\rShowtimeIDTwo\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x0fShowtimeDateTwo\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t2\x9b\x03\n\x07\x42ooking\x12)\n\nGetBooking\x12\t.EmptyTwo\x1a\x0c.BookingData\"\x00\x30\x01\x12-\n\x12GetBookingByUserId\x12\x07.UserID\x1a\x0c.BookingData\"\x00\x12*\n\nAddBooking\x12\x0c.BookingData\x1a\x0c.BookingData\"\x00\x12-\n\rDeleteBooking\x12\x0c.BookingData\x1a\x0c.BookingData\"\x00\x12-\n\rUpdateBooking\x12\x0c.BookingData\x1a\x0c.BookingData\"\x00\x12\x31\n\x0eGetShowtimeTwo\x12\t.EmptyTwo\x1a\x10.ShowtimeDataTwo\"\x00\x30\x01\x12:\n\x14GetShowtimeByDateTwo\x12\x0e.ShowtimeIDTwo\x1a\x10.ShowtimeDataTwo\"\x00\x12=\n\x15GetShowtimeByMovieTwo\x12\x10.ShowtimeDateTwo\x1a\x10.ShowtimeDataTwo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTYTWO']._serialized_start=17
  _globals['_EMPTYTWO']._serialized_end=27
  _globals['_USERID']._serialized_start=29
  _globals['_USERID']._serialized_end=53
  _globals['_BOOKINGDATA']._serialized_start=55
  _globals['_BOOKINGDATA']._serialized_end=107
  _globals['_DATES']._serialized_start=109
  _globals['_DATES']._serialized_end=146
  _globals['_SHOWTIMEDATATWO']._serialized_start=148
  _globals['_SHOWTIMEDATATWO']._serialized_end=195
  _globals['_SHOWTIMEIDTWO']._serialized_start=197
  _globals['_SHOWTIMEIDTWO']._serialized_end=224
  _globals['_SHOWTIMEDATETWO']._serialized_start=226
  _globals['_SHOWTIMEDATETWO']._serialized_end=257
  _globals['_BOOKING']._serialized_start=260
  _globals['_BOOKING']._serialized_end=671
# @@protoc_insertion_point(module_scope)
